import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { withAppTRPC } from "./utils/withTRPC";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>          
        {children}
      </body>
    </html>
  );
}

export default RootLayout
